#* Copyright (C) 2024  Wiktor Perskawiec <contact@spageektti.cc>
#
#? This program is free software: you can redistribute it and/or modify
#? it under the terms of the GNU General Public License as published by
#? the Free Software Foundation, either version 3 of the License, or
#? (at your option) any later version.
#
#! This program is distributed in the hope that it will be useful,
#! but WITHOUT ANY WARRANTY; without even the implied warranty of
#! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#! GNU General Public License for more details.
#
#* You should have received a copy of the GNU General Public License
#* along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: Build APK on Push to Main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"

      - name: Install dependencies
        run: flutter pub get

      - name: Update build number
        run: |
          sed -i -E 's/(version:.*\+)([0-9]+)/echo "\1$((\2 + 1))"/e' pubspec.yaml

      - name: Build APK
        run: flutter build apk --release

      - name: Create checksums
        run: |
          cd build/app/outputs/flutter-apk
          sha256sum app-release.apk > app-release.apk.sha256
          sha1sum app-release.apk > app-release.apk.sha1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk-artifacts
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/flutter-apk/app-release.apk.sha256
            build/app/outputs/flutter-apk/app-release.apk.sha1
