name: Build and Release APK

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Create checksums
        run: |
          cd build/app/outputs/flutter-apk
          sha256sum app-release.apk > app-release.apk.sha256
          sha1sum app-release.apk > app-release.apk.sha1

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-apk-artifacts
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/flutter-apk/app-release.apk.sha256
            build/app/outputs/flutter-apk/app-release.apk.sha1

      - name: Upload APK and checksums to release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.event.release.tag_name }}
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/flutter-apk/app-release.apk.sha256
            build/app/outputs/flutter-apk/app-release.apk.sha1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
